### ISSUE TITLE
Helm install fails without default curly braces in values file config mapping

### ISSUE THREAD

**Issue by a1031** [volker-raschek/drone-runner-charts#2]
Hi, thank you for creating and maintaining this chart (and the server chart)! I just started using both today (version `0.3.1`) and ran into this minor issue.

I'd pulled/untar'd the chart locally. Without making any edits to the chart or `values.yaml` and running this:
```
helm install drone-runner volker.raschek/drone-runner \
   -f drone-runner/values.yaml \
   --set "config.DRONE_NAMESPACE_DEFAULT=drone" \
   --set "config.DRONE_RPC_HOST=drone" \
   --set "config.DRONE_RPC_PROTO=https" \
   --set "config.DRONE_RPC_SECRET=secret"
```
I get this error:
```
Error: INSTALLATION FAILED: failed parsing --set data: unable to parse key: interface conversion: interface {} is nil, not map[string]interface {}
```
If I happened to do the install without any `set` overrides it works, but, of course, there are required values which need to be set.

I'd then found that it works if I add the default empty curly braces to the `config:` mapping (similar to how it is in the Drone server chart [here](https://github.com/volker-raschek/drone-charts/blob/master/values.yaml#L30)):
```
...
config: {}
  # DRONE_ANNOTATIONS_DEFAULT
  # Optional string map. Provides a set of default annotations used when
...
```
And it also works if I'd omitted the values overrides file altogether.

Was there a reason those default empty curly braces were omitted?

**Comment by volker-raschek** [comment]
Hi @a1031, 
thank you very much for the tip. I have added the missing brackets and created a new release. Now the helm command should work.
